# Generated by Django 3.1.7 on 2021-02-27 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articles',
            options={'verbose_name': 'Блог', 'verbose_name_plural': 'Блог'},
        ),
    ]
