# Generated by Django 3.1.7 on 2021-03-06 16:38

from django.db import migrations, models
import taggit.managers
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articles',
            options={'verbose_name': 'Блог', 'verbose_name_plural': 'Блог'},
        ),
        migrations.AddField(
            model_name='articles',
            name='link',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Ссылка на детальную страницу'),
        ),
        migrations.AddField(
            model_name='articles',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Теги'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='anons',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Анонс'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='full_text',
            field=tinymce.models.HTMLField(verbose_name='Статья'),
        ),
    ]
