# Generated by Django 3.1.7 on 2021-02-28 22:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210227_1935'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='link',
            field=models.CharField(default=django.utils.timezone.now, max_length=50, verbose_name='Ссылка на детальную страницу'),
            preserve_default=False,
        ),
    ]
