# Generated by Django 3.1.7 on 2021-03-04 16:33

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_articles_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='full_text',
            field=tinymce.models.HTMLField(verbose_name='Статья'),
        ),
    ]
