# Generated by Django 3.1.7 on 2021-03-04 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20210304_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='anons',
            field=models.CharField(blank=True, max_length=250, verbose_name='Анонс'),
        ),
    ]
