# Generated by Django 3.1.7 on 2021-03-04 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20210304_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='anons',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Анонс'),
        ),
    ]
