# Generated by Django 3.1.7 on 2021-03-06 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20210304_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='link',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Ссылка на детальную страницу'),
        ),
    ]
