# Generated by Django 3.1.7 on 2021-03-06 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20210306_1558'),
        ('blog', '0002_auto_20210306_1638'),
    ]

    operations = [
    ]
