# Generated by Django 3.1.7 on 2021-03-06 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_merge_20210306_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='link',
            field=models.SlugField(blank=True, default='asas', verbose_name='Ссылка на детальную страницу'),
            preserve_default=False,
        ),
    ]
