# Generated by Django 3.1.7 on 2021-03-06 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20210306_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='link',
            field=models.SlugField(verbose_name='Ссылка на детальную страницу'),
        ),
    ]
