# Generated by Django 3.1.7 on 2021-03-06 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20210306_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='link',
            field=models.SlugField(help_text='Если автоматически сгенерированная ссылка вам не подходить, то измените ее ручной', unique=True, verbose_name='Ссылка на детальную страницу'),
        ),
    ]
