# Generated by Django 3.1.7 on 2021-03-06 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20210306_2105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='anons',
            field=models.CharField(blank=True, help_text='Если оставить пустой, то анонс создаться из первого абзаца новости!', max_length=250, null=True, verbose_name='Анонс'),
        ),
    ]
