# Generated by Django 3.1.7 on 2021-03-06 21:42

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaticPages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Называние страниц')),
                ('slug', models.SlugField(max_length=20, unique=True, verbose_name='Ссылка')),
                ('page_code', tinymce.models.HTMLField(verbose_name='Код страницы')),
            ],
            options={
                'verbose_name': 'Статическая страница',
                'verbose_name_plural': 'Статические страницы',
            },
        ),
    ]
