# Generated by Django 3.1.7 on 2021-03-06 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_staticpages'),
    ]

    operations = [
        migrations.AddField(
            model_name='staticpages',
            name='menu',
            field=models.BooleanField(default='True', verbose_name='Добавить в меню'),
            preserve_default=False,
        ),
    ]
